# Generated by Django 2.2 on 2021-05-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_Bundels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_paths', models.FileField(upload_to='pdfs')),
            ],
            options={
                'db_table': 'Pdf_Bundels',
            },
        ),
    ]
