# Generated by Django 2.2 on 2021-05-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pdf_bundels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='pdf_path',
        ),
    ]
